I32 mixingmatrix
statnet/network pull request #50
Opened 2021-01-12 00:15 UTC by mbojan

Simpler object returned by `mixiningmatrix()`, closes #32:

- it is of class `c("mixingmatrix", "table")` with logical attributes `directed` and `bipartite`
- added `[[` and `$` methods for backward compatibility. The are `.Deprecated`
- made `is.directed()` and `is.bipartite()` generic with added methods for mixing matrices
- documented the value returned
- updated tests

2021-01-12 02:16 UTC, mbojan commented
I will still fix via this PR:

```
── R CMD check results ───────────────────────────────── network 1.17.0-585 ────
Duration: 1m 5.5s

❯ checking Rd \usage sections ... WARNING
  Undocumented arguments in documentation object 'network.indicators'
    ‘...’
  
  Functions with \usage entries need to have the appropriate \alias
  entries, and all their arguments documented.
  The \usage entries must correspond to syntactically valid R code.
  See chapter ‘Writing R documentation files’ in the ‘Writing R
  Extensions’ manual.

❯ checking files in ‘vignettes’ ... WARNING
  Files in the 'vignettes' directory but no files in 'inst/doc':
    ‘networkVignette.Rnw’, ‘networkVignette.pdf’

❯ checking package vignettes in ‘inst/doc’ ... WARNING
  dir.exists(dir) is not TRUE
  Package vignette without corresponding single PDF/HTML:
     ‘networkVignette.Rnw’

❯ checking CRAN incoming feasibility ... NOTE
  Maintainer: ‘Carter T. Butts <buttsc@uci.edu>’
  
  Unknown, possibly mis-spelled, fields in DESCRIPTION:
    ‘Remotes’
  
  The Date field is over a month old.

❯ checking R code for possible problems ... NOTE
  print.mixingmatrix: no visible global function definition for
    ‘addmargins’
  Undefined global functions or variables:
    addmargins
  Consider adding
    importFrom("stats", "addmargins")
  to your NAMESPACE file.

0 errors ✔ | 3 warnings ✖ | 2 notes ✖
```

2021-01-14 01:57 UTC, mbojan commented
Ready.

2021-01-18 08:49 UTC, krivit requested changes
Thanks for the enhancement!

2021-01-18 08:49 UTC, krivit commented on R/misc.R
> +
Can you please remove the extraneous whitespace?

2021-01-18 08:49 UTC, krivit commented on R/misc.R
> +
Ditto.

2021-01-18 14:29 UTC, mbojan commented on R/misc.R
> +
Will do

2021-01-20 06:00 UTC, krivit commented
No comments from Carter, so I'll go ahead and merge.

2021-01-20 06:00 UTC, merged